### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by fzyzcjy** [Purus/launch_review#27]
Hi in flutter 2.0 null safety is stable, so hope this wonderful package can migrate to 2.0

**Comment by fzyzcjy** [comment]
PR https://github.com/Purus/launch_review/pull/28

**Comment by RR-Reddy** [comment]
@fzyzcjy looks like author not yet published into pub.dev

**Comment by Purus** [comment]
@fzyzcjy Package has been published. Please verify and let me know if there any issues. Thanks again for your contribution.
