### ISSUE TITLE
3.0.0 version not working in both Android and IOS

### ISSUE THREAD

**Issue by RR-Reddy** [Purus/launch_review#29]
**Android error log** 
![Screenshot 2021-03-08 at 5 39 46 AM](https://user-images.githubusercontent.com/32235964/110260145-098c1580-7fd1-11eb-9914-5cc89184b466.png)

**Ios error log**
![Screenshot 2021-03-08 at 5 35 16 AM](https://user-images.githubusercontent.com/32235964/110260155-11e45080-7fd1-11eb-9320-6d4acec6b1ce.png)

**Android gradle build error log** 
![Screenshot 2021-03-08 at 5 38 44 AM](https://user-images.githubusercontent.com/32235964/110260190-33453c80-7fd1-11eb-9ec2-3b89b79f95b0.png)

**Note :**
![Screenshot 2021-03-08 at 5 40 45 AM](https://user-images.githubusercontent.com/32235964/110260255-5f60bd80-7fd1-11eb-8aa1-91f242185739.png)

1) Not working when i am using version 3.0.0 
2) Working as expected  when i am pointing to git url

**Comment by fzyzcjy** [comment]
is the `example` app run sucessfully?

**Comment by RR-Reddy** [comment]
@fzyzcjy issue  reproduced  in **example** project

please see line no : **19** and **error log in console**

![Screenshot 2021-03-08 at 7 25 38 AM](https://user-images.githubusercontent.com/32235964/110264610-bb324300-7fdf-11eb-8c2b-ef7e2395818d.png)

Note : I am thinking there may be something went wrong in release process

**Comment by fzyzcjy** [comment]
Hmm my null-safety migration seems to be unrelated with this.

Maybe caused by this merge? https://github.com/Purus/launch_review/commit/11c9dcdbe1ad89a84437f228b7f6e027ef7a691f

@Purus

**Comment by nohli** [comment]
Could you try? It should fix it :)

```
  launch_review:
    git:
      url: https://github.com/nohli/launch_review
      ref: fix-flutter-2
```

**Comment by RR-Reddy** [comment]
@nohli i could test it when it is available in pub.dev along with your changes. because when i am pointing to git repo as dependency i am not facing any issues

**Comment by nohli** [comment]
@RR-Reddy so maybe the issue is not in this code...

I just downloaded the pub.dev version and there were 84 changed files compared to this repo's master.

For example (red is this repo, green the pub.dev version):

![1](https://user-images.githubusercontent.com/43643339/110337177-e9d30c80-8025-11eb-853e-6d4ae4285ef7.png)

Maybe the added 'platforms' part is wrong.

**Comment by fzyzcjy** [comment]
@RR-Reddy So does 3.0.1 work for you?
