### ISSUE TITLE
On iOS, when the app is not on Apple App Store calling LaunchReview.launch() makes the app crash.

### ISSUE THREAD

**Issue by quentinleguennec** [Purus/launch_review#3]
I didn't test this crash on Android.

**Comment by harishbalasubramanian** [comment]
Yeah I also have this issue on IOS

**Comment by Panthro** [comment]
Even when app is on appstore but calling from simulator app crashes

**Comment by Purus** [comment]
Thanks for reporting the issue. I couldn't test the issue as I don't have
Mac/iOS.

Can you please let me know if it's possible for you to debug? I am happy to
accept the pull request.

Thanks,

Purusothaman Ramanujam

**Comment by erickcchoi** [comment]
flutter 0.10.2 on Android simulator/app crashes

**Comment by Purus** [comment]
Please try the v2.0.0 and let me if it works.

Create a new issue if you still face the issue.

**Comment by Purus** [comment]
> Even when app is on appstore but calling from simulator app crashes

I believe this plugin does not work with iOS Simulator. As I don't have knowledge on iOS or Mac.
